name:                servant-options
version:             0.1.0.0
-- synopsis:
-- description:
homepage:            https://github.com/githubuser/servant-options#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - servant-server
  - servant-foreign
  - wai
  - bytestring
  - text
  - http-types

library:
  source-dirs:      src
