name:                servant-options
version:             0.1.0.0
synopsis:            Provide responses to OPTIONS requests for Servant applications.
description:         Provide responses to OPTIONS requests for Servant applications.
homepage:            https://github.com/sordina/servant-options
license:             MIT
author:              Lyndon Maydwell
maintainer:          maydwell@gmail.com
copyright:           2017 Lyndon Maydwell
category:            Web
extra-source-files:  [ 'README.md' ]

dependencies:
  - base >= 4.7 && < 5
  - servant-server
  - servant-foreign
  - wai
  - bytestring
  - text
  - http-types

library:
  source-dirs:      src
